"""Outbound contracts owned by the application; adapters satisfy them structurally."""

from dataclasses import dataclass, field
from typing import Literal, Protocol

from ..domain.context import ContextDocument, ContextSection
from ..domain.models import CareerProfile, FillPlan, FormInspection, JobRole, SourceSnapshot


class ProfileRepository(Protocol):
    def load_profile(self) -> CareerProfile: ...
    def save_profile(self, profile: CareerProfile) -> None: ...


class ContextRepository(Protocol):
    def load_context(self, section: ContextSection) -> ContextDocument | None: ...
    def save_context(self, document: ContextDocument) -> str: ...
    def context_path(self, section: ContextSection) -> str: ...
    def initialize_notes(self, template: str) -> str: ...


class MatchingRepository(ProfileRepository, Protocol):
    def load_jobs(self) -> list[JobRole]: ...
    def existing_jobs(self) -> list[JobRole]: ...
    def save_jobs(self, jobs: list[JobRole]) -> None: ...
    def save_source(self, document: SourceSnapshot) -> str: ...
    def save_recommendations(self, report: dict) -> None: ...


class AutofillRepository(ProfileRepository, Protocol):
    def load_plan(self, plan_id: str) -> FillPlan: ...
    def save_plan(self, plan: FillPlan) -> None: ...
    def save_fill_report(self, report: dict) -> None: ...


class SourceReader(Protocol):
    async def read(self, url: str) -> SourceSnapshot: ...


class JobSource(Protocol):
    async def collect(self) -> tuple[list[JobRole], list[dict[str, str]]]: ...
    def parse(self, document: SourceSnapshot) -> list[JobRole]: ...


@dataclass
class BrowserBatchResult:
    filled_ids: set[str] = field(default_factory=set)
    errors: list[dict] = field(default_factory=list)
    field_checks: int = 0


class ApplicationBrowser(Protocol):
    async def open_application(self, job_url: str, mode: Literal["new", "existing"]) -> dict: ...
    async def inspect(self) -> FormInspection: ...
    async def execute(self, plan: FillPlan) -> BrowserBatchResult: ...
    async def close(self) -> None: ...
